### ISSUE TITLE
Fatal Error when importing the cldr-segmentation module

### ISSUE THREAD

**Issue by batatop** [camertron/cldr-segmentation.js#13]
Hello, I'm trying to use the package on my `React` application. However, when I try to import `cldr-segmentation` module, I get an error saying: `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`.

I don't call any functions, I just require or import the module. It looks like this:
`import cldrSegmentation from 'cldr-segmentation'`
or
`require('cldr-segmentation')`

Am I doing something wrong? Thank you for your concern.

**Comment by camertron** [comment]
Hey @batatop, thanks for reaching out. I've never seen that error before, but after a quick Google search it sounds like it's caused by your `node` process running out of memory: https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas

While cldr-segmentation does ship with a few semi-large state table arrays, we're talking at most a couple hundred kilobytes of memory. My guess is you were already really close to the memory limit and adding cldr-segmentation pushed you over the top.

According to the top SO answer, you could try switching to a later version of Node - maybe that's an easy fix? The other option would be to increase the amount of memory `node` is allowed to use.

**Comment by batatop** [comment]
@camertron , thanks for the response. I didn't think that you would answer that quickly :D If I increase the Node's memory limit, do you think the users can still experience the issue?

Also, I tested the package on [Code Sandbox](https://codesandbox.io) to see if it will work outside of my Node environment. But when I try to `console.log(cldr-segmentation)`, I get `undefined`. So I started to think that I'm doing something wrong. Can you please check this link? https://codesandbox.io/s/recursing-haze-hswl0

**Comment by camertron** [comment]
Hey @batatop, did you see the error in a browser or in a `node` process?

Ok, I think the problem you're running into when trying to `import` the module is because cldr-segmentation only supports AMD/commonjs, i.e. is not an es6 module. I never personally needed it to work with es6, but it's probably a good idea to add support for it. I can look into that later this week.

In the meantime, try this after your import statements:

```javascript
const cldrSegmentation = require("cldr-segmentation");
```

**Comment by batatop** [comment]
@camertron I saw the memory error that I mentioned on a `node` process. 

> I never personally needed it to work with es6, but it's probably a good idea to add support for it. I can look into that later this week.

That would be amazing! I did a lot of research to find something similar to your project. I'm trying to split Thai (or similar languages with no whitespace) sentences word by word but I couldn't find a library that would do it on client. Because all the solutions that I found required dictionaries that would require a large space. I think [Intl.Segmenter](https://github.com/tc39/proposal-intl-segmenter) will be released for this purpose but I'm not sure when. Therefore, this library could be very beneficial for a lot of people. Thank you very much!

Edit: I think I've already tried `const cldrSegmentation = require("cldr-segmentation");` but I'll test it today, as soon as possible.

**Comment by camertron** [comment]
Hmm interesting. Unfortunately I don't think cldr-segmentation.js is going to work for you if you're looking to segment Thai, Khmer, Burmese, Chinese, etc. All the implementations I'm aware of require dictionaries to identify word boundaries. I tried adding that functionality to cldr-segmentation.js, but the dictionaries - even when encoded as tries - are very large (like 400k for Chinese). I'm sure there's a way to make them smaller, but I couldn't figure it out :(

**Comment by batatop** [comment]
@camertron I see, thank you for the heads up. I will close this issue. If you know a lightweight solution for languages like Thai, can you kindly let me know? I have to find a way to handle this on the client. Either way, thank you for taking the time to explain the issue.

**Comment by camertron** [comment]
Hey @batatop, I've managed to get the Thai dictionary down to about 62kb. What size would you say is acceptable for the browser?

**Comment by batatop** [comment]
@camertron That's great! However, I needed a solution for all languages. There are other languages like Chinese, Khmer, etc. that don't have whitespaces. On Chrome, there is `v8BreakIterator` that provides functions to separate words in any language. So I implemented the feature there and showed a popup on the rest of the browsers. I'll probably keep it that way until [Intl.Segmenter](https://github.com/tc39/proposal-intl-segmenter) arrives.

I really appreciate your help and support. And thank you for your great library!

**Comment by camertron** [comment]
@batatop ah ok, glad you've found a solution :) The Thai dictionary I mentioned was only an example, I also have dictionaries for Chinese/Japanese, Burmese, Khmer, and Laotian. The largest one is the CJ dictionary, which is 1.3mb :(

In any case, using the native v8BreakIterator is probably the best way to go because it's likely based on ICU, which is the industry standard implementation hehe.

**Comment by briunsilo** [comment]
I run into the same issues when trying to use this library in a react application.

Steps to reproduce:
1. Create app by running `npx create-react-app cldr-segmentation`
2. Add dependency `"cldr-segmentation": "^2.1.0"` to package.json and run `npm install`
3. Add `const cldrSegmentation = require('cldr-segmentation');` to `App.js`
4. Run `npm start`

Platform: Mac
Node: v12.14.1
npm: 6.13.4

**Comment by camertron** [comment]
Hey @batatop and @briunsilo, I was able to reproduce this on my machine and isolate the problem. I've published v2.1.1 with the fix. It looks like something (maybe webpack?) didn't like the semi-large arrays that make up the segmentation state tables. I serialized them as strings instead and that seems to have done the trick.

**Comment by batatop** [comment]
@camertron great news! Thank you for taking the time to look into this.
