### ISSUE TITLE
Cannot read property 'stringToCodePoints' of undefined

### ISSUE THREAD

**Issue by dylan904** [camertron/cldr-segmentation.js#16]
Getting this error when using a vanilla JS environment.
https://codesandbox.io/s/smoosh-bash-zrotq?file=/src/index.js

**Comment by tonton-pixel** [comment]
@dylan904 I got the same error message when trying to install and use this library in an application built with the Electron framework. To work around this issue and run the code successfully, I had to explicitely install the previous version v2.1.1 instead of the current default v2.1.2, i.e., I ran the following command from CLI:

    npm install cldr-segmentation@v2.1.1

**Comment by camertron** [comment]
Hey @dylan904 and @tonton-pixel, I was able to figure out the problem and have published v2.1.3. Let me know if that fixes your issues :)

**Comment by tonton-pixel** [comment]
@camertron No more error message in v2.1.3. Thank you!
