### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by porkopek** [camertron/cldr-segmentation.js#5]
Hi!

I tried to do a simple sentence segmentation of a text with just 1000 words and it lasts several seconds (more than 10 ) in the browser. 
How can I improve the segmentation time?

I'm using sentenceSplit method with no exceptions

Thanks

**Comment by camertron** [comment]
Hey @porkopek, sadly this lib is pretty inefficient because it implements the segmentation rules as regular expressions under the hood. I ported it straight from [twitter-cldr-rb](https://github.com/twitter/twitter-cldr-rb) which uses the same strategy.

The good news is I realized how slow it was a while ago and started working on a faster implementation that uses state machines. The rewrite has proven much more difficult than I anticipated, so the work has sort of stalled. If you speak Ruby, take a look at [this branch](https://github.com/twitter/twitter-cldr-rb/tree/dictionary_segmentation). I was hoping to port it to Javascript when it's 100% working. So far it's failing around 200/1900 of the Unicode conformance tests.

**Comment by porkopek** [comment]
Oh, thanks! I hope you will be successful in this task.

Good luck :-)

**Comment by camertron** [comment]
Hey @porkopek, I just published v2.0 of the library, which is much, much faster than v1.0. If you're still in need of a segmentation implementation, feel free to give it a spin :)

**Comment by porkopek** [comment]
Thanks! I will take a look
